### ISSUE TITLE
Tester le menu hamburger

### ISSUE THREAD

**Issue by axel584** [axel584/samopiniuloj-por-android#10]
http://www.androidhive.info/2013/11/android-sliding-menu-using-navigation-drawer/ http://codetheory.in/android-navigation-drawer/
http://www.tutos-android.com/navigationdrawer-android-naviguer-1
http://blog.teamtreehouse.com/add-navigation-drawer-android
http://www.android4devs.com/2014/12/how-to-make-material-design-navigation-drawer.html

**Comment by axel584** [comment]
http://www.androidhive.info/2013/11/android-sliding-menu-using-navigation-drawer/
http://codetheory.in/android-navigation-drawer/

**Comment by axel584** [comment]
http://blog.teamtreehouse.com/add-navigation-drawer-android
http://www.android4devs.com/2014/12/how-to-make-material-design-navigation-drawer.html

**Comment by emmrichard** [comment]
https://stinkyparkia.wordpress.com/tag/appcompat-v7/
