### ISSUE TITLE
Changement de page quand on change l'orientation 

### ISSUE THREAD

**Issue by emmrichard** [axel584/samopiniuloj-por-android#71]
Quand on change l'orientation de l'appareil, on retrouve la page précédente.

Exemple :
- on est sur la page Eniri (mode portrait)
- dans le menu, on choisit Kiel ludi
  --> la page Kiel ludi s'affiche
- on passe en mode paysage
  --> la page Eniri réapparaît

**Comment by axel584** [comment]
c'est corrigé (en fait, la création de l'activité lançait "par défaut" ludi ou eniri (si on était connecté ou non) et il fallait d'abord vérifié si le fragment dans le fragmentmanager était "non null"...
