### ISSUE TITLE
Dans "eniri", ignorer les espaces à la fin du nom d'utilisateur

### ISSUE THREAD

**Issue by emmrichard** [axel584/samopiniuloj-por-android#81]
Par exemple si je tape "emmanuelle ", ça devait être accepté de la même façon que si je tape "emmanuelle" (ça fonctionne comme ça sur le site

**Comment by axel584** [comment]
corrigé dans le webservice

**Comment by axel584** [comment]
mais ça ne fonctionne pas :-(

**Comment by emmrichard** [comment]
Je viens d'essayer sur ma tablette et ça fonctionne.
J'ai essayé avec 1 espace, puis 2 espaces.
Essaie encore, peut être que ça va marcher ?
