### ISSUE TITLE
Au retour dans l'appli, les mots déjà enregistrés n'ont plus leur coche verte

### ISSUE THREAD

**Issue by emmrichard** [axel584/samopiniuloj-por-android#83]
pour reproduire le cas :
1. se connecter sur son compte
2. saisir quelques mots pour le mot du jour puis cliquer sur SENDU
   --> après validation, les coches vertes sont affichées
3. quitter et fermer le jeu
4. rouvrir l'appli
   --> la page du jeu est réaffichée telle qu'elle était, mais il manque les coches vertes.
5. taper un mot suppémentaire puis le bouton SENDU
   --> la coche verte apparaît sur le nouveau mot mais pas les anciens
6. aller sur la page "kiel ludi" puis revenir sur la page "ludi"
   --> cette fois, toutes les coches sont affichées

**Comment by axel584** [comment]
Je n'arrive pas à le reproduire sur l'émulateur.

**Comment by emmrichard** [comment]
Moi non plus, je n'arrive plus à reproduire le bug. Peut-être que tu l'as corrigé en corrigeant autre chose ?
